### ISSUE TITLE
🐛 Bug Tracking Help 🪲

### ISSUE THREAD

**Issue by PowerLevel9000** [yodit93/school_library#5]
# 🪲 Bug Tracking Help 🐛
# Hi @yodit93 , 

Good job so far!
I have spotted the Bug you are dealing with right now take a look at the comment and highlight too for celebration
<br >

![AmericanPsychoImpressiveGIF](https://github.com/yodit93/school_library/assets/116451144/75af300a-111e-4e37-bc15-0ba03eafab00)

## Highlights :heavy_check_mark: 
- [x] Git flow is used correctly :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark: 
- [x] Clean code :white_check_mark:   
 

## Bug Spotted 🔫🔫🔫

I can say your approach was Good and impressive to make your code Dry  but you can improve it more see the `optional Suggestion` section for reference

## The Bug explanation
- [ ] Your code saying `self` for [this ](https://github.com/yodit93/school_library/blob/12d44c53087b5c19cd16cd996f11f2d5558a4681/person.rb#L18) line which means the creating instance `class(self)` not `inherited class`  
- [ ] Which means `person.all` means for person instance according to [this ](https://github.com/yodit93/school_library/blob/12d44c53087b5c19cd16cd996f11f2d5558a4681/person.rb#L40) line will give you all the instances of `persons` created by `Person.new` not child one  
- [ ] Lastly, as you inherited  with `person` you can access all of your methods from the person class therefore you can use `Student.all` to print student created by `Student.new` and same with `Teacher` 

- On top of this , Kindly remove [these ](https://github.com/yodit93/school_library/blob/12d44c53087b5c19cd16cd996f11f2d5558a4681/app.rb#L115) lines for weird behavior of the console
![image](https://github.com/yodit93/school_library/assets/116451144/f5dae4ab-6ee6-429a-9cfd-0281cbbb52a4)
- Check this code output for clear reference 
```
require_relative 'student'
require_relative 'classroom'
require_relative 'person'
require_relative 'book'
require_relative 'rental'
puts "***************** from test.rb for Debugging *************"
student = Student.new(28, name:"ghgfdsf")
print 'from person => '
puts !Person.all[0] ? "nill" : Person.all[0].name 
print "from student => "
puts !Student.all[0] ? "nill" : Student.all[0].name 
person = Person.new(28, "adarsh")
print 'from person direct creation => '
puts !Person.all[0] ? "nill" : Person.all[0].name

```

![image](https://github.com/yodit93/school_library/assets/116451144/2ff2a0c2-c930-446b-bf65-17e777d0ca95)

 

## Optional suggestions
- [ ] Kindly, make a module or A decorator which will do the same thing for you like storing each class instance in an array and printing it with all you just need to inherit or include it where you want linting 🙃🙃🥂🥂💪 in this way your code Follows the Dry approach efficiently  

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by yodit93** [comment]
Thank you
